# Generated by Django 5.2.7 on 2025-10-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_manage', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(null=True, upload_to='car_manage/'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
